# Generated by Django 4.2.3 on 2023-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
