# Generated by Django 5.0.1 on 2024-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studyresource',
            fields=[
                ('subjectid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('chaptername', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('booktitle', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
