# Generated by Django 5.0.1 on 2024-02-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyresource',
            old_name='booktitle',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studyresource',
            old_name='subjectid',
            new_name='courseid',
        ),
        migrations.RemoveField(
            model_name='studyresource',
            name='chaptername',
        ),
        migrations.RemoveField(
            model_name='studyresource',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='studyresource',
            name='subject',
        ),
    ]
