# Generated by Django 5.0.1 on 2024-02-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socline', '0002_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
