# Generated by Django 5.0.1 on 2024-02-28 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socline', '0004_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRoom',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('slug', models.CharField(max_length=130)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socline.serverroom')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socline.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
