# Generated by Django 5.0.1 on 2024-02-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socline', '0005_serverroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverroom',
            name='slug',
        ),
    ]
