# Generated by Django 5.0.1 on 2024-02-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socline', '0006_remove_serverroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverroom',
            name='post',
        ),
        migrations.RemoveField(
            model_name='serverroom',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='serverroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='ServerRoom',
        ),
    ]
